---
deployment:
  tasks:
    - export DEPLOYPATH=/home/trailslab/public_html/
    - export VENVPATH=/home/trailslab/rubyvenv/repositories_trails-lab/3.2/bin/activate
    - export DEPLOYPATH=/home/trailslab/public_html/ && export VENVPATH=/home/trailslab/rubyvenv/repositories_trails-lab/3.2/bin/activate && source $VENVPATH && bundle install && bundle exec jekyll build -d $DEPLOYPATH